version: "3"

services:
    webapi:
        image: docker-dotnetcore/webapi:develop
        build:
            context: ../WebApi
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            MongoDB__Host: mongo
            # - ASPNETCORE_ENVIRONMENT=Development
            # - ASPNETCORE_URLS=http://+:5000
        depends_on: 
            - mongo
            - elasticsearch
    client:
        image: docker-dotnetcore/client:develop
        build:
            context: ../Client
            dockerfile: Dockerfile
        depends_on:
            - webapi
            - elasticsearch
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8088:8088
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
        depends_on:
            - mongo
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
        ports:
            - "9200:9200"