version: "3"

services:
    webapi:
        image: docker-dotnetcore/webapi:develop
        build:
            context: ../WebApi
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
    client:
        image: docker-dotnetcore/client:develop
        build:
            context: ../Client
            dockerfile: Dockerfile
        depends_on:
            - webapi
